feat: do not expand variables that contain passwords
snyk/broker pull request #386
Opened 2022-02-21 23:02 UTC by yeforriak

Avoid expanding variables that contain passwords since passwords may contain `$` symbols 

- [x] Ready for review
- [x] Follows [CONTRIBUTING](https://github.com/snyk/broker/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### Screenshots

#### Additional questions

2022-02-22 09:38 UTC, ar-snyk approved these changes
no issues found

2022-02-22 10:31 UTC, carlos-snyk requested changes

2022-02-22 10:31 UTC, carlos-snyk commented on lib/config.js
> +  ];
The Broker code doesn't know anything about SCMs or their env vars. I think it should stay that way

2022-02-22 10:35 UTC, carlos-snyk commented on lib/config.js
> +  ];
Maybe the solution is to have an env var with the property names that contain secrets.

`ENV_VARS_CONTAINING_PASSWORDS="BROKER_CLIENT_VALIDATION_AUTHORIZATION_HEADER, BROKER_CLIENT_VALIDATION_BASIC_AUTH"`

2022-05-25 17:10 UTC, obenn commented
Issue addressed in https://github.com/snyk/broker/pull/406, suggest close if 406 merged

2022-05-25 23:08 UTC, closed without merging