fix: set the group to root on the node home folder
snyk/broker pull request #421
Opened 2022-07-27 18:41 UTC by enzo-cappa

- [x] Ready for review
- [x] Follows [CONTRIBUTING](https://github.com/snyk/broker/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?

On Openshift it's required that all files are owned by the root group,
and with all perms set. This is because the images run with a randomly
assigned user id, but part of the root group. See
https://docs.openshift.com/container-platform/4.9/openshift_images/create-images.html#images-create-guide-openshift_create-images

#### Where should the reviewer start?

Only one file was changed, but it's good to take a look at https://docs.openshift.com/container-platform/4.9/openshift_images/create-images.html#images-create-guide-openshift_create-images

#### How should this be manually tested?

Run latest broker Bitbucket image on Openshift

2022-07-27 18:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/snyk/broker?pullRequest=421) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/snyk/broker?pullRequest=421) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/snyk/broker?pullRequest=421) it.</sub>

2022-07-28 09:43 UTC, attriaayush submitted a review, later dismissed

2022-08-01 08:40 UTC, attriaayush approved these changes

2022-08-01 09:02 UTC, ipsi commented
This would only fix the issue for the BitBucket Broker Client, leaving all the other images with potential issues. If we're going to fix this, I'd prefer a solution that fixes all the images.

2022-08-01 09:03 UTC, attriaayush requested changes
https://github.com/snyk/broker/pull/421#issuecomment-1200921192

2022-08-02 14:12 UTC, enzo-cappa commented
Will be handled in a different way.

2022-11-21 17:43 UTC, Jimimaku commented
> [![CLA assistant check](https://camo.githubusercontent.com/777a078050c6b0e4f4af5f36272b0014312f4cafeea86f96c172ea30870fb940/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f7369676e6564)](https://cla-assistant.io/snyk/broker?pullRequest=421) All committers have signed the CLA.

2023-05-10 19:15 UTC, closed without merging