fix: disable xff by default for nexus broker clients
snyk/broker pull request #483
Opened 2023-01-31 13:40 UTC by aarlaud

- [x] Ready for review

#### What does this PR do?

Disables the XFF headers for nexus broker clients by default to avoid nexus returning invalid npm tarball uris.

2023-01-31 14:01 UTC, ipsi requested changes, later dismissed

2023-01-31 14:01 UTC, ipsi commented on client-templates/nexus2/.env.sample
> +removeXForwardedHeaders=true
Recommend making it consistent with the other env vars.
```suggestion
REMOVE_X_FORWARDED_HEADERS=true
```

2023-01-31 14:01 UTC, ipsi commented on client-templates/nexus/.env.sample
> +removeXForwardedHeaders=true
Recommend making it consistent with the other env vars.
```suggestion
REMOVE_X_FORWARDED_HEADERS=true
```

2023-02-05 21:26 UTC, pavel-snyk approved these changes
LGTM

2023-02-06 09:07 UTC, merged

2023-02-06 09:09 UTC, snyksec commented
:tada: This PR is included in version 4.141.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/snyk-broker/v/4.141.3)
- [GitHub release](https://github.com/snyk/broker/releases/tag/v4.141.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: